// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: ctogo.proto

package ctogo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdID int32

const (
	CmdID_HEART_BEAT      CmdID = 0
	CmdID_QUERY_USER_INFO CmdID = 1
)

// Enum value maps for CmdID.
var (
	CmdID_name = map[int32]string{
		0: "HEART_BEAT",
		1: "QUERY_USER_INFO",
	}
	CmdID_value = map[string]int32{
		"HEART_BEAT":      0,
		"QUERY_USER_INFO": 1,
	}
)

func (x CmdID) Enum() *CmdID {
	p := new(CmdID)
	*p = x
	return p
}

func (x CmdID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdID) Descriptor() protoreflect.EnumDescriptor {
	return file_ctogo_proto_enumTypes[0].Descriptor()
}

func (CmdID) Type() protoreflect.EnumType {
	return &file_ctogo_proto_enumTypes[0]
}

func (x CmdID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdID.Descriptor instead.
func (CmdID) EnumDescriptor() ([]byte, []int) {
	return file_ctogo_proto_rawDescGZIP(), []int{0}
}

type QueryUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
}

func (x *QueryUserInfoReq) Reset() {
	*x = QueryUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ctogo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserInfoReq) ProtoMessage() {}

func (x *QueryUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_ctogo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserInfoReq.ProtoReflect.Descriptor instead.
func (*QueryUserInfoReq) Descriptor() ([]byte, []int) {
	return file_ctogo_proto_rawDescGZIP(), []int{0}
}

func (x *QueryUserInfoReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type QueryUserInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Money    uint32 `protobuf:"fixed32,3,opt,name=Money,proto3" json:"Money,omitempty"`
}

func (x *QueryUserInfoRsp) Reset() {
	*x = QueryUserInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ctogo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserInfoRsp) ProtoMessage() {}

func (x *QueryUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_ctogo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserInfoRsp.ProtoReflect.Descriptor instead.
func (*QueryUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_ctogo_proto_rawDescGZIP(), []int{1}
}

func (x *QueryUserInfoRsp) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *QueryUserInfoRsp) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *QueryUserInfoRsp) GetMoney() uint32 {
	if x != nil {
		return x.Money
	}
	return 0
}

var File_ctogo_proto protoreflect.FileDescriptor

var file_ctogo_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x74, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x74, 0x6f, 0x67, 0x6f, 0x22, 0x2e, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x60, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x07, 0x52,
	0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x2a, 0x2c, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x44, 0x12,
	0x0e, 0x0a, 0x0a, 0x48, 0x45, 0x41, 0x52, 0x54, 0x5f, 0x42, 0x45, 0x41, 0x54, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x49, 0x4e,
	0x46, 0x4f, 0x10, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x67, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x63, 0x74, 0x6f, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ctogo_proto_rawDescOnce sync.Once
	file_ctogo_proto_rawDescData = file_ctogo_proto_rawDesc
)

func file_ctogo_proto_rawDescGZIP() []byte {
	file_ctogo_proto_rawDescOnce.Do(func() {
		file_ctogo_proto_rawDescData = protoimpl.X.CompressGZIP(file_ctogo_proto_rawDescData)
	})
	return file_ctogo_proto_rawDescData
}

var file_ctogo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ctogo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ctogo_proto_goTypes = []interface{}{
	(CmdID)(0),               // 0: ctogo.CmdID
	(*QueryUserInfoReq)(nil), // 1: ctogo.QueryUserInfoReq
	(*QueryUserInfoRsp)(nil), // 2: ctogo.QueryUserInfoRsp
}
var file_ctogo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ctogo_proto_init() }
func file_ctogo_proto_init() {
	if File_ctogo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ctogo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ctogo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUserInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ctogo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ctogo_proto_goTypes,
		DependencyIndexes: file_ctogo_proto_depIdxs,
		EnumInfos:         file_ctogo_proto_enumTypes,
		MessageInfos:      file_ctogo_proto_msgTypes,
	}.Build()
	File_ctogo_proto = out.File
	file_ctogo_proto_rawDesc = nil
	file_ctogo_proto_goTypes = nil
	file_ctogo_proto_depIdxs = nil
}
